# Generated by Django 4.2.4 on 2023-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database_Siemens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
