# Generated by Django 4.2.4 on 2023-09-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_ETL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_siemens',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='database_siemens',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
