apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-django-app-2
  template:
    metadata:
      labels:
        app: my-django-app-2
    spec:
      containers:
        - name: my-django-container-2
          image: {{ .Values.appimage}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-django-service-2
spec:
  selector:
    app: my-django-app-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer